#mysql
spring:
 datasource:
  url: jdbc:mysql://10.1.45.38:3306/demo_database?useSSL=false&allowPublicKeyRetrieval=true
  username: igaps
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
